### ISSUE TITLE
Message board

### ISSUE THREAD

**Issue by bee25141** [the-ravenclaw-sisterhood/project-deuce#9]

**Comment by zapmi** [comment]
-chat created
-need to deploy to Heroku

https://github.com/heroku-examples/node-socket.io

**Comment by zapmi** [comment]
-need to integrate into main files

**Comment by zapmi** [comment]
-After speaking to Paul, we decided to create a new heroku app just for the chat.
-App has been deployed to heroku & everything is now working
-need to replace the username prompt with username from sql db
